language: java

install: skip

script: skip

after_script:
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" develop:master

branches:
  only:
    - develop

env:
  global:
    - GH_REF: github.com/azhengZJ/zuji-jpa.git

